#
# © 2026-present Godot Mobile Plugins (https://github.com/godot-mobile-plugins)
#

platform_version=14.3
swift_version=5.9
frameworks=Foundation.framework,AudioToolbox.framework,UIKit.framework
embedded_frameworks=
flags=-ObjC
bundle_files=

# -- Test configuration --------------------------------------------------------
test_platform=iOS Simulator
test_destination_name=iPhone 17
test_os=latest
